apiVersion: apps/v1
kind: Deployment
metadata:
  name: springdeploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springlabel
  template:
    metadata:
      name: springpod
      labels:
        app: springlabel
    spec:
      containers:
      - name: springcontainer
        image: premadocker90/spring-boot-mongo:1
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_DB_HOSTNAME
          value: mongoservice
        - name: MONGO_DB_USERNAME
          value: prema
        - name: MONGO_DB_PASSWORD
          value: prema
---
apiVersion: v1
kind: Service
metadata:
  name: springservice
spec:
  type: NodePort
  selector:
    app: springlabel
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mongorc
spec:
  selector:
    app: mongolabel
  template:
    metadata:
      name: mongopod
      labels:
        app: mongolabel
    spec:
      containers:
      - name: mongocontainer
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: prema
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: prema
---
apiVersion: v1
kind: Service
metadata:
  name: mongoservice
spec:
  type: ClusterIP
  selector:
    app: mongolabel
  ports:
  - port: 27017
    targetPort: 27017

